"""add_cart_actions_table

Revision ID: 0d271db948d7
Revises: 9322c2c77bdd
Create Date: 2026-01-21 15:10:21.926762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d271db948d7'
down_revision: Union[str, None] = '9322c2c77bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_events_name', table_name='events')
    op.drop_index('ix_events_project_id', table_name='events')
    op.drop_index('ix_events_visit_id', table_name='events')
    op.drop_table('events')
    op.add_column('cart_actions', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.add_column('cart_actions', sa.Column('action', sa.String(), nullable=False))
    op.add_column('cart_actions', sa.Column('product_url', sa.String(), nullable=True))
    op.alter_column('cart_actions', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_cart_actions_session_id', table_name='cart_actions')
    op.drop_index('ix_cart_actions_visitor_id', table_name='cart_actions')
    op.create_foreign_key(None, 'cart_actions', 'visits', ['visit_id'], ['id'])
    op.drop_column('cart_actions', 'visitor_id')
    op.drop_column('cart_actions', 'product_category')
    op.drop_column('cart_actions', 'product_price')
    op.drop_column('cart_actions', 'action_type')
    op.drop_column('cart_actions', 'session_id')
    op.drop_column('cart_actions', 'quantity')
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('cart_actions', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart_actions', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_actions', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart_actions', sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cart_actions', sa.Column('product_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_actions', sa.Column('visitor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_actions', type_='foreignkey')
    op.create_index('ix_cart_actions_visitor_id', 'cart_actions', ['visitor_id'], unique=False)
    op.create_index('ix_cart_actions_session_id', 'cart_actions', ['session_id'], unique=False)
    op.alter_column('cart_actions', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cart_actions', 'product_url')
    op.drop_column('cart_actions', 'action')
    op.drop_column('cart_actions', 'visit_id')
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='events_project_id_fkey'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name='events_visit_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_index('ix_events_visit_id', 'events', ['visit_id'], unique=False)
    op.create_index('ix_events_project_id', 'events', ['project_id'], unique=False)
    op.create_index('ix_events_name', 'events', ['name'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    # ### end Alembic commands ###
