"""Add team_invites table

Revision ID: 41a489c4c35b
Revises: db2f6178b297
Create Date: 2026-03-19 15:33:09.424395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41a489c4c35b'
down_revision: Union[str, None] = 'db2f6178b297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_session_id', table_name='chat_history')
    op.drop_index('ix_chat_history_user_id', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chat_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey'),
    sa.UniqueConstraint('session_id', name='chat_history_session_id_key')
    )
    op.create_index('ix_chat_history_user_id', 'chat_history', ['user_id'], unique=False)
    op.create_index('ix_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
