"""Add OTP fields to team_invites table

Revision ID: 4325f8f61b68
Revises: defe1d9d45fb
Create Date: 2026-03-20 15:59:50.295849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4325f8f61b68'
down_revision: Union[str, None] = 'defe1d9d45fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_invites', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('team_invites', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('team_invites', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('team_invites', sa.Column('is_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_invites', 'is_accepted')
    op.drop_column('team_invites', 'is_verified')
    op.drop_column('team_invites', 'otp_expiry')
    op.drop_column('team_invites', 'otp')
    # ### end Alembic commands ###
