"""initial

Revision ID: 9322c2c77bdd
Revises: 6e81b0f92a74
Create Date: 2025-12-31 16:21:45.584403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9322c2c77bdd'
down_revision: Union[str, None] = '6e81b0f92a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_resets_email', table_name='password_resets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_password_resets_email', 'password_resets', ['email'], unique=False)
    # ### end Alembic commands ###
