"""fix_events_table_structure

Revision ID: 9dd3b02e067a
Revises: ff9b10cd7fb2
Create Date: 2026-03-11 11:17:19.196012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dd3b02e067a'
down_revision: Union[str, None] = 'ff9b10cd7fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exit_links_id', table_name='exit_links')
    op.drop_table('exit_links')
    op.add_column('events', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('events', sa.Column('event_data', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_index('ix_events_event_name', table_name='events')
    op.drop_index('ix_events_project_id', table_name='events')
    op.drop_index('ix_events_session_id', table_name='events')
    op.drop_index('ix_events_visitor_id', table_name='events')
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.drop_constraint('events_project_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'visits', ['visit_id'], ['id'])
    op.drop_column('events', 'visitor_id')
    op.drop_column('events', 'session_id')
    op.drop_column('events', 'page_url')
    op.drop_column('events', 'event_properties')
    op.drop_column('events', 'event_name')
    op.drop_column('events', 'project_id')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('event_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('page_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('visitor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_project_id_fkey', 'events', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.create_index('ix_events_visitor_id', 'events', ['visitor_id'], unique=False)
    op.create_index('ix_events_session_id', 'events', ['session_id'], unique=False)
    op.create_index('ix_events_project_id', 'events', ['project_id'], unique=False)
    op.create_index('ix_events_event_name', 'events', ['event_name'], unique=False)
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.drop_column('events', 'timestamp')
    op.drop_column('events', 'url')
    op.drop_column('events', 'event_data')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'visit_id')
    op.create_table('exit_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_page', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_clicked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='exit_links_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exit_links_pkey')
    )
    op.create_index('ix_exit_links_id', 'exit_links', ['id'], unique=False)
    # ### end Alembic commands ###
