"""cleanup_removed_tables

Revision ID: d14fd30cc580
Revises: 33d3f71c6308
Create Date: 2026-02-25 15:55:21.861568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd14fd30cc580'
down_revision: Union[str, None] = '33d3f71c6308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_script_verifications_id', table_name='script_verifications')
    op.drop_table('script_verifications')
    op.drop_index('ix_install_checks_domain', table_name='install_checks')
    op.drop_index('ix_install_checks_id', table_name='install_checks')
    op.drop_table('install_checks')
    op.drop_index('ix_email_reports_id', table_name='email_reports')
    op.drop_table('email_reports')
    op.drop_index('ix_script_installations_domain', table_name='script_installations')
    op.drop_index('ix_script_installations_id', table_name='script_installations')
    op.drop_index('ix_script_installations_project_id', table_name='script_installations')
    op.drop_table('script_installations')
    op.drop_table('alembic_versions')
    op.drop_column('projects', 'verified_at')
    op.drop_column('projects', 'is_verified')
    op.drop_column('projects', 'allowed_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('allowed_domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('alembic_versions',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_versions_pkey')
    )
    op.create_table('script_installations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('install_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='script_installations_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='script_installations_pkey')
    )
    op.create_index('ix_script_installations_project_id', 'script_installations', ['project_id'], unique=False)
    op.create_index('ix_script_installations_id', 'script_installations', ['id'], unique=False)
    op.create_index('ix_script_installations_domain', 'script_installations', ['domain'], unique=False)
    op.create_table('email_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='email_reports_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_reports_pkey')
    )
    op.create_index('ix_email_reports_id', 'email_reports', ['id'], unique=False)
    op.create_table('install_checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_pings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='install_checks_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='install_checks_pkey')
    )
    op.create_index('ix_install_checks_id', 'install_checks', ['id'], unique=False)
    op.create_index('ix_install_checks_domain', 'install_checks', ['domain'], unique=False)
    op.create_table('script_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ping_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='script_verifications_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='script_verifications_pkey')
    )
    op.create_index('ix_script_verifications_id', 'script_verifications', ['id'], unique=False)
    # ### end Alembic commands ###
