"""add_user_projects_table

Revision ID: defe1d9d45fb
Revises: 41a489c4c35b
Create Date: 2026-03-19 17:21:18.070151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'defe1d9d45fb'
down_revision: Union[str, None] = '41a489c4c35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_members_id', table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name='team_members_added_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='team_members_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='team_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_members_pkey')
    )
    op.create_index('ix_team_members_id', 'team_members', ['id'], unique=False)
    # ### end Alembic commands ###
